// <auto-generated />
using System;
using Blog.Abstractions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blog.Abstractions.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Blog.Abstractions.Entitys.ArticlePraise", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlogNum");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.HasKey("KID");

                    b.ToTable("ArticlePraises");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Blogcontent", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BloginfoNum")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.HasKey("KID");

                    b.ToTable("Blogcontents");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Bloginfo", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlogNum")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Blogimg");

                    b.Property<int>("Comments");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<int>("IsOriginal");

                    b.Property<int>("IsPrivate");

                    b.Property<int>("IsTop");

                    b.Property<sbyte>("Sorc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<int>("Start");

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("Type");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("Vesion");

                    b.Property<int>("Views")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(1);

                    b.HasKey("KID");

                    b.HasIndex("Type");

                    b.ToTable("Bloginfos");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Category", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int>("Description");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<int>("FatherId");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.HasKey("KID");

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            KID = 1,
                            CreateTime = new DateTime(2019, 9, 9, 9, 9, 9, 0, DateTimeKind.Unspecified),
                            Description = 0,
                            FatherId = 0,
                            IsDeleted = (sbyte)0,
                            Name = "efcore",
                            States = (sbyte)0,
                            UpdateTime = new DateTime(2020, 3, 4, 22, 34, 45, 7, DateTimeKind.Local).AddTicks(5211),
                            UpdateUserId = "1",
                            UpdateUserName = "System内置"
                        });
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Categorypic", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("KID");

                    b.ToTable("Categorypics");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Comment", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("BlogNum")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Commentid")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Memberid")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("ToMemberid")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.HasKey("KID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Employee", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<int>("IsAdmin");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<DateTime>("LastUpTime");

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UserAcount")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("UserNikeName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("KID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            KID = 1,
                            CreateTime = new DateTime(2019, 9, 9, 9, 9, 9, 0, DateTimeKind.Unspecified),
                            IsAdmin = 1,
                            IsDeleted = (sbyte)0,
                            LastUpTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            States = (sbyte)0,
                            UpdateTime = new DateTime(2020, 3, 4, 22, 34, 45, 27, DateTimeKind.Local).AddTicks(5802),
                            UpdateUserId = "1",
                            UpdateUserName = "System内置",
                            UserAcount = "123",
                            UserName = "超级管理员",
                            UserNikeName = "超管",
                            UserPassword = "202CB962AC59075B964B07152D234B70"
                        });
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.HotNew", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("Title");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("Url");

                    b.HasKey("KID");

                    b.ToTable("HotNews");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Logintoken", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUserId");

                    b.Property<string>("CreateUserName");

                    b.Property<int?>("Extend1");

                    b.Property<int?>("Extend2");

                    b.Property<int?>("Extend3");

                    b.Property<string>("Extend4");

                    b.Property<string>("Extend5");

                    b.Property<string>("Extend6");

                    b.Property<string>("IpAddr");

                    b.Property<int>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("IsLogOut");

                    b.Property<string>("LoginResult");

                    b.Property<string>("LoginUserAccount");

                    b.Property<string>("LoginUserId");

                    b.Property<int>("LoginUserType");

                    b.Property<int>("PlatForm");

                    b.Property<int>("States")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Token");

                    b.Property<string>("TokenExpiration");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("UpdateUserId");

                    b.Property<string>("UpdateUserName");

                    b.HasKey("KID");

                    b.ToTable("Logintokens");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Media", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<int>("Type");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("Url");

                    b.HasKey("KID");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Member", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UserAccount");

                    b.Property<string>("UserIcon");

                    b.Property<string>("UserName");

                    b.Property<string>("UserPassword");

                    b.HasKey("KID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Operationlog", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1");

                    b.Property<int?>("Extend2");

                    b.Property<int?>("Extend3");

                    b.Property<string>("Extend4");

                    b.Property<string>("Extend5");

                    b.Property<string>("Extend6");

                    b.Property<string>("IpAddr");

                    b.Property<int>("IsDeleted");

                    b.Property<string>("LogContent");

                    b.Property<int>("OperResult");

                    b.Property<int>("OperType");

                    b.Property<string>("ReqData");

                    b.Property<string>("ResOldData");

                    b.Property<string>("ResResult");

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("TableName");

                    b.Property<string>("TablePriKeyField");

                    b.Property<string>("TablePriKeyValue");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("UpdateUserId");

                    b.Property<string>("UpdateUserName");

                    b.HasKey("KID");

                    b.ToTable("Operationlogs");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Sysmenu", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<int>("Fatherid");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("MenuUrl")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Menuicon")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Menuname")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Menuremark")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("Menusort");

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.HasKey("KID");

                    b.ToTable("Sysmenus");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Sysrole", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("MenuList")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Roleremark")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.HasKey("KID");

                    b.ToTable("Sysroles");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Sysuserrole", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1");

                    b.Property<int?>("Extend2");

                    b.Property<int?>("Extend3");

                    b.Property<string>("Extend4");

                    b.Property<string>("Extend5");

                    b.Property<string>("Extend6");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<int>("Roleid");

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<int>("UserType")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("Userid");

                    b.HasKey("KID");

                    b.HasIndex("Roleid");

                    b.HasIndex("Userid");

                    b.ToTable("Sysuserroles");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.WxUser", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1970, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("1");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("System");

                    b.Property<int?>("Extend1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Extend3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Extend4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend5")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("Extend6")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("");

                    b.Property<string>("HeadImgUrl")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Openid")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Privilege")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<sbyte>("States")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("Unionid")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.Property<string>("UpdateUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasDefaultValue("");

                    b.HasKey("KID");

                    b.ToTable("WxUsers");
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Bloginfo", b =>
                {
                    b.HasOne("Blog.Abstractions.Entitys.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Blog.Abstractions.Entitys.Sysuserrole", b =>
                {
                    b.HasOne("Blog.Abstractions.Entitys.Sysrole", "Sysrole")
                        .WithMany("Sysuserroles")
                        .HasForeignKey("Roleid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Blog.Abstractions.Entitys.Employee", "Employee")
                        .WithMany("Sysuserroles")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
